ansible_user: Administrator@SUMMIT2019.LOCAL
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62663564303262376638626132636638656236666635376135343366643032643830303338333963
          3033373434316231616638383132343231366431623861610a376665373939303462383936626639
          39653734663730333638656133343930303634333534343333653635633339636638656665373138
          3935656434383831310a666436373330353135643938656263643163396437383137313438326230
          36663031633863303830383335333762646230386134653239616466316163613735
ansible_connection: winrm
ansible_port: 5985
ansible_winrm_transport: kerberos
ansible_winrm_message_encryption: always